### ISSUE TITLE
Full path on node click (Related to issue #8)

### ISSUE THREAD

**Issue by Kurtaja** [m-thalmann/treejs#10]
I'm trying to modify your example in 'issue #8' with the aim of producing a string containing the whole path from root to the clicked node, hence for my modification I was hoping to get the string "root - 1 - 1.1".
The only difference between your test in 'issue #8' and mine is within your "on/select" function (see mine below). However I don't manage to get it to run properly. The fist alert, only showing the selected folder ("1.1"), pops up alright. But the rest of the alert's are ignored, so I'm surely doing something wrong (no exeption's are thrown though). After "countless" trial/errors I'm running out of ideas what to try next. Do you have the possibility to point me in the good direction?

n11.on('select', function (e) {
alert(e);
var mySelNode = tree.getSelectedNodes();
alert("1");
path.setPath(root, mySelNode);
alert("2");
path.getPath();
alert("3");
alert(path.toString());
})

**Comment by Kurtaja** [comment]
I'm sure there are way more elegant ways to do this, but in case anybody else are struggling with the same thing, this function works for what I was looking for:


    function getTreePathFromClickedNode(nodeClicked) {
        var nodeAbove = null;
        let sFolderName = "";
        let sClickedPath = "";
        let iCnt = 0;
        try {
            do {
                sFolderName = "";
                if (nodeClicked.parent) {
                    nodeAbove = nodeClicked.parent;
                    sFolderName = nodeAbove.getChildren().toString();
                    if (iCnt == 0) {
                        sClickedPath = sFolderName;
                        iCnt++;
                    }
                    else {
                        sClickedPath = sFolderName + "/" + sClickedPath;
                    }
                    nodeClicked = nodeAbove;
                }
            } while (nodeClicked.parent);
            
        }
        catch (err) {
            alert("Error in function getTreePathFromClickedNode: " + err.message);
        }
        return sClickedPath;
    }

**Comment by m-thalmann** [comment]
Hi!
If you just want the path from the root-node to a given node (like for example when clicking on it) you could use the following function. The function returns the path as list of nodes:

```js
function getNodePathToRoot(node) {
	let parentNode = node.parent;

	if(typeof parentNode === 'undefined') {
		return [node];
	}

	return getNodePathToRoot(parentNode).concat([node]);
}
```

Example usage:

```js
n11.on('select', function (e) {
	let path = getNodePathToRoot(e);

	// this could be done using the Array.prototype.reduce() function
        let stringPath = '';
	path.forEach(function(node) {
		stringPath += node.getUserObject();
	});

	alert(stringPath);
});
```

Does this fit your usecase?

**Comment by Kurtaja** [comment]
Thanks Matthias!
Your recursive function is much more elegant than mine!
However, I had to modify it slightly to fit my usecase:
1)
Added "/" after each folder in the path string (and removed the first and last "/" in the resulting path string).
2)
Removed the "root" text in the path (because even if I initialized the 'TreeView' function using an option object with 'show_root: false' before creating the nodes and rather call redraw afterwards, it still showed the root name). 
3)
**Question**: The last child node in each expanded branch is always drawn with an 'unknown' icon while all the parent nodes are drawn with the 'folder' icon. What do I need to do to draw the last child node with the 'folder' icon too?

Here are the modifications that fit my usecase (you probably want to make a more elegant implementation if you deside to bring it into your libray though :-)):



function myTreejsGetNodePathToRoot(node) {
    // Recursive function for getting the path from clicked node to root
    let parentNode = node.parent;

    if (typeof parentNode === 'undefined') {
        return [node];
    }
    return myTreejsGetNodePathToRoot(parentNode).concat([node]);
}


function myTreejsGetTreePathFromClickedNode(nodeClicked, bRemoveRootFolderName, sRootFolderName) {
    //Returns the path from a node clicked in tree.js.
    let sClickedPath = "";
    try {
        if (nodeClicked != null) {
            let path = myTreejsGetNodePathToRoot(nodeClicked);
            path.forEach(function (node) {
                sClickedPath += node.getUserObject() + "/";
            });
            if (bRemoveRootFolderName) {
                sClickedPath = sClickedPath.replace(sRootFolderName, "");
            }
            if (sClickedPath.indexOf("/") > -1) {
                sClickedPath = sClickedPath.substr(0, sClickedPath.length - 1)
            }
            if (sClickedPath.length > 0) {
                if (sClickedPath[0] == '/') {
                    sClickedPath = sClickedPath.substr(1, sClickedPath.length - 1)
                }
            }
        }
    }
    catch (err) {
        alert("Error in function storage_vs_project.myTreejsGetTreePathFromClickedNode: " + err.message);
    }
    return sClickedPath;
}

**Comment by m-thalmann** [comment]
Hi again.
To answer your question: This is possible with one of these options:

1. Set the `forceParent` option for a specific node, so it will always be displayed as if it had children. Example:
```js
var n1 = new TreeNode("1", { forceParent: true });
```

2. Set the icon for a specific node using the `icon` option. Example:
```js
var n2 = new TreeNode("2", { icon: TreeUtil.default_parent_icon }); // this uses the default folder icon, but you can also use a custom one
```

3. Set the default leaf-icon in the options (node without children). Example:
```js
TreeConfig.leaf_icon = TreeUtil.default_parent_icon; // can be any icon you want
```

**Comment by Kurtaja** [comment]
Thanks, that worked :-) !

**Comment by m-thalmann** [comment]
I'm glad, no worries!
Closing this issue since all questions have been answered.
