### ISSUE TITLE
Invalid condition for non-string user objects

### ISSUE THREAD

**Issue by Blumster** [m-thalmann/treejs#2]
In the constructor of TreeNode, the check for the type of userObject (is it string or an object with a toString function) is wrong.

Currently if the userObject is a string, it checks if it has a toString function (it does).
If the userObject is not a string, it errors, without checking the toString function.

It should look like this:
`if(typeof userObject !== "string" && typeof userObject.toString !== "function")`

**Comment by m-thalmann** [comment]
You are totally right! I'll fix it asap. Thanks!
