### ISSUE TITLE
HTML tags in the node name

### ISSUE THREAD

**Issue by Blumster** [m-thalmann/treejs#3]
The HTML tags are not escaped in the node's name.

If it is intended, an option to turn on encoding should be added.
If it is not intended and encoding will be added, an option to turn it off should be added too.

**Comment by m-thalmann** [comment]
@Blumster I tried to set the nodes content to an HTML tag like shown:
```js
var n1 = new TreeNode("<a href=\"#1\">Test</a>");
```

This resulted in expected behaviour:
![grafik](https://user-images.githubusercontent.com/30590624/102689514-ff8f1d80-41fe-11eb-9a7b-4ee33df3505c.png)

Unless you can provide a counter example, I assume it is working.

**Comment by Blumster** [comment]
My problem is that I don't want it to render HTML tags. There should be an option to escape the HTML code.

If you set "< TEST >" (without spaces) as the name, the folder/file comes up without a name, as it was interpreted as an HTML tag.

**Comment by m-thalmann** [comment]
You can simply use the HTML characters like `&lt;` for `<` or use an escape function like the following:
```js
function escapeHtml(unsafe) {
    return unsafe
         .replace(/&/g, "&amp;")
         .replace(/</g, "&lt;")
         .replace(/>/g, "&gt;")
         .replace(/"/g, "&quot;")
         .replace(/'/g, "&#039;");
 }
```
Source: https://stackoverflow.com/a/6234804/11028838

**Comment by Blumster** [comment]
If it uses client supplied data, that's when it would be good to have an option like this.

Yes, ofc I can use a function like that, just I was interested if official built in support could be done for this.

Thanks anyways!
