### ISSUE TITLE
Problem with Bootstrap Modal?

### ISSUE THREAD

**Issue by a-serra** [m-thalmann/treejs#6]
There is any problem using this script with a container inside a bootstrap modal? Because i am trying to make it working, but I cannot.
Thanks and great work!

**Comment by m-thalmann** [comment]
Could you provide an example of this and clearify exactly what you mean?

**Comment by a-serra** [comment]
I open my modal window in this way:

```js
        function addModal(item) {
            var modalInstance = modal.open({
                templateUrl: '/app/attachFolder/modal/attachFolderAdd.html?version=15',
                controller: 'attachFolderAdd',
                backdrop: 'static',
                resolve: {
                    tSource: function () {
                        return vm.tSource;
                    },
                    rootId: function () {
                        return vm.fatherId;
                    }

                }
            });
```

in the corresponding JS file, I define the tree in the way:
```js
        var root = new TreeNode("ROOT");

        $scope.tSource.forEach(function (item) {
            if (item.ParentId == rootId) {
                root.addChild(new TreeNode(item.Name));
            }
        });

        var view = new TreeView(root, '#container');
```

In the console appears the warning **tree.js?version=1:122 No container specified** even if I define the container in the html file.
Using bootstrap could be a problem?

EDIT: I also try to use **document.getElementById("container")** but the result is the same.

**Comment by m-thalmann** [comment]
Could you show me a full working example, so that I can test this for my self? (Maybe put it on pastebin or something)
But I understand your problem.

**Comment by a-serra** [comment]
Resolved! It was a problem of "priority" of read the js first than html (so the script doesn't see the container).
