### ISSUE TITLE
pop tree with Hash ?

### ISSUE THREAD

**Issue by MatrixFr** [m-thalmann/treejs#7]
can we make tree from hash JSON ? like :

` {name: "root", childs: [{name: "node1"}, {name: "node2", childs: [...]}]`

**Comment by m-thalmann** [comment]
Yes, of course. But you have to implement it yourself.

Example:
```js
var data = [{name: "root", children: [{name: "node1"}, {name: "node2", children: [...]}]}];

var root = new TreeNode("root");

function addChildren(node, data){
  data.forEach(function(nodeData){
    var _node = new TreeNode(nodeData.name);

    if(nodeData.children && nodeData.children.length > 0){
      addChildren(_node, nodeData.children);
    }

    node.addChild(_node);
  });
}

addChildren(root, data);
```

**Comment by MatrixFr** [comment]
ok, and if I want load asynchroneously the tree, I can ajax to get data from specific node, add nodes with this function and just rafrech with tree.reload(), right ?

**Comment by m-thalmann** [comment]
Yes exactly!
