### ISSUE TITLE
Question: how to use node events?

### ISSUE THREAD

**Issue by amaczuga** [m-thalmann/treejs#8]
Assigning a callback to a "select", or "click" events makes the callback function fire for all nodes during initial load, then doesn't react to clicks/selection. 
What am I doing wrong?

```
child = new TreeNode(value);
child.on('select', console.log(value));
a.addChild(child);
```

**Comment by m-thalmann** [comment]
@amaczuga hi! I have tried to reproduce this but for me it does work correctly. Can you share the full snippet of the tree so I can try it for myself?

The example I used (which worked):

```js
var root = new TreeNode("root");
	var n1 = new TreeNode("1");
		var n11 = new TreeNode("1.1");
	var n2 = new TreeNode("2");
	var n3 = new TreeNode("3");
		var n31 = new TreeNode("3.1");
		var n32 = new TreeNode("3.2");
			var n321 = new TreeNode("3.2.1");
		var n33 = new TreeNode("3.3");

n11.on('select', function(e) {
	console.log(e);
})

root.addChild(n1);
root.addChild(n2);
root.addChild(n3);

n1.addChild(n11);

n3.addChild(n31);
n3.addChild(n32);
n3.addChild(n33);

n3.setEnabled(false);

n32.addChild(n321);

var view = new TreeView(root, "#container");
```

**Comment by amaczuga** [comment]
@m-thalmann oh. my bad. instead of passing the function as callback, I completely abused the method. please disregard. 

thank you for your attention : )

**Comment by Kurtaja** [comment]
I'm trying to modify your example above with the aim of producing a string containing the whole path from root to the clicked node, hence for this example I was hoping to get the string "root - 1 - 1.1". 
The only difference between your test above and mine is within your "on/select" function (see mine below). However I don't manage to get it to run properly. The fist alert, only showing the selected folder ("1.1"), pops up alright. But the rest of the alert's are ignored, so I'm surely doing something wrong (no exeption's are thrown though). After "countless" trial/errors I'm running out of ideas what to try next. Do you have the possibility to point me in the good direction?

n11.on('select', function (e) {
  alert(e);
  var mySelNode = tree.getSelectedNodes();
  alert("1");
  path.setPath(root, mySelNode);
  alert("2");
  path.getPath();
  alert("3");
  alert(path.toString());
})
